### ISSUE TITLE
Can't control devices with ios app

### ISSUE THREAD

**Issue by ccc11223** [CdriFry/C4_HarmonyHub#1]
I just installed the drivers and believe everything was setup per the documentation. When I launch an activity via the C4 ios app the harmony activity starts correctly, turns on the tv, and devices, sets inputs etc. I am able to control volume but none of the other buttons seem to control my devices. The arrows, menu, cancel etc. are all unresponsive when pressed. Any suggestions. I've tried an Apple TV and a blu-ray player that both are controlled via my harmony elite remote without problem

**Comment by CdriFry** [comment]
Hello, thank you for your interest in my project. Could I have some additional information such as the version and model of your director control4, I will recheck this evening (Brussels time) by putting myself in the same configuration as you.
Ced.

**Comment by ccc11223** [comment]
I’m on the latest version. I believe 3.41 and an EA5 controller.   
  

  
Thank you   
  
  
  
  
  
  
  

  
  
>

**Comment by CdriFry** [comment]
Good news, I was able to reproduce your issue on a EA1, it seems that the problem comes from the way the TV is recorded or not like the media service distributor. Try removing your "fake" TV (Not visible on Navigators) and replacing it, connecting the HDMI connection to AV OUT, refresh, and test.

If that still doesn't work, use a simplest IR-controlled TV (Samsung UN32EH4000F for example..) with an HDMI port in the "Connections" section.

**Comment by CdriFry** [comment]
It seems that connecting the room's "Video's audio endpoint 1" to the Harmony Hub fixed the issue.
